SELECT 
    DISTINCT
    #SEGMENT.SEGMENT_TYPE_CODE,
    #SEGMENT.TICKET_STATUS_TYPE_CODE,
 
    HOTEL_ITINERARY_SEGMENT.CHECK_IN_LOCATION,      
    HOTEL_ITINERARY_SEGMENT.HOTEL_NAME,     
    DATE_FORMAT(SEGMENT.CREATED, '%d-%m-%Y')  AS 'Created Date',
    DATE_FORMAT(HOTEL_ITINERARY_SEGMENT.CHECK_IN_DATE, '%d-%m-%Y') AS 'Check-in Date',  
    DATE_FORMAT(HOTEL_ITINERARY_SEGMENT.CHECK_OUT_DATE, '%d-%m-%Y') AS 'Check-out Date',
    SEGMENT.BOOKING_ID,
  
    DATEDIFF(HOTEL_ITINERARY_SEGMENT.CHECK_OUT_DATE,HOTEL_ITINERARY_SEGMENT.CHECK_IN_DATE) as room_nights,
    HOTEL_ITINERARY_SEGMENT.NUMBER_OF_ROOMS,  

    COSTING.SUPPLIER_RATES_EXCL_GST,
    (COSTING.SUPPLIER_RATES_EXCL_GST / DATEDIFF (HOTEL_ITINERARY_SEGMENT.CHECK_OUT_DATE, HOTEL_ITINERARY_SEGMENT.CHECK_IN_DATE) ) 
    / HOTEL_ITINERARY_SEGMENT.NUMBER_OF_ROOMS AS AVERAGE_ROOM_RATE,
    
    COSTING.SUPPLIER_FEES_EXCL_GST   
    (COSTING.SUPPLIER_FEES_EXCL_GST / DATEDIFF (HOTEL_ITINERARY_SEGMENT.CHECK_OUT_DATE, HOTEL_ITINERARY_SEGMENT.CHECK_IN_DATE) ) 
    / HOTEL_ITINERARY_SEGMENT.NUMBER_OF_ROOMS AS AVERAGE_SUPPLIER_FEES
       
    #SERVICE_FEE_COSTING_SEGMENT.GROSS_FEE_AMOUNT_EXCL_GST
    
FROM ttms_nexuspointtravelnz.SEGMENT
LEFT OUTER JOIN ttms_nexuspointtravelnz.BOOKING ON SEGMENT.BOOKING_ID = BOOKING.BOOKING_ID 
LEFT OUTER JOIN ttms_nexuspointtravelnz.COSTING ON SEGMENT.COSTING_ID = COSTING.COSTING_ID
LEFT OUTER JOIN ttms_nexuspointtravelnz.HOTEL_ITINERARY_SEGMENT ON SEGMENT.SEGMENT_ID = HOTEL_ITINERARY_SEGMENT.SEGMENT_ID
LEFT OUTER JOIN ttms_nexuspointtravelnz.SERVICE_FEE_COSTING_SEGMENT ON SEGMENT.SEGMENT_ID = SERVICE_FEE_COSTING_SEGMENT.SEGMENT_ID
WHERE 
    
SEGMENT.SEGMENT_TYPE_CODE = 'HOTEL'
    AND BOOKING.STATUS_TYPE_CODE  IN ('FINALISED','BOOKED')
    AND SEGMENT.TICKET_STATUS_TYPE_CODE = 'TICKET_ISSUE'
    AND SEGMENT.SEGMENT_STATUS_TYPE_CODE = 'ACTIVE'
    AND SEGMENT.CREATED BETWEEN '2017/07/01 00:00:00' AND '2018/06/30 00:00:00'
    AND SEGMENT.TRAVEL_TYPE_CODE = 'TRANS_TASMAN'
    AND HOTEL_ITINERARY_SEGMENT.HOTEL_NAME IN ('Travelodge Wellington', 'Novotel Auckland Ellerslie', 'CORDIS  AUCKLAND', 'Quality Hotel Napier', 'Copthorne Hotel Oriental Bay', 'Copthorne Hotel Palmerston','Ibis Auckland Ellerslie', 'Novotel Wellington', 'Copthorne Hotel Palmerston North', 'Quality Inn Napier');
    #AND HOTEL_ITINERARY_SEGMENT.CHECK_IN_LOCATION = 'DBO';
